//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingFriends.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActorRoleMapping
    {
        public int MappingID { get; set; }
        public Nullable<int> ActorID { get; set; }
        public Nullable<int> ActorRoleID { get; set; }
        public Nullable<decimal> CustomRatePerHour { get; set; }
    
        public virtual Actors Actors { get; set; }
        public virtual ActorRoles ActorRoles { get; set; }
    }
}
