//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingFriends.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actors
    {
        public Actors()
        {
            this.ActorRoleMapping = new HashSet<ActorRoleMapping>();
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int ActorID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<bool> IsDrinkable { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
    
        public virtual ICollection<ActorRoleMapping> ActorRoleMapping { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
