//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingFriends.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActorRoles
    {
        public ActorRoles()
        {
            this.ActorRoleMapping = new HashSet<ActorRoleMapping>();
            this.OrderDetails = new HashSet<OrderDetails>();
            this.ScriptRequiredRoles = new HashSet<ScriptRequiredRoles>();
        }
    
        public int ActorRoleID { get; set; }
        public string RoleName { get; set; }
        public decimal BaseRatePerHour { get; set; }
    
        public virtual ICollection<ActorRoleMapping> ActorRoleMapping { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ICollection<ScriptRequiredRoles> ScriptRequiredRoles { get; set; }
    }
}
