//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingFriends.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLogs
    {
        public int LogID { get; set; }
        public Nullable<int> AdminUserID { get; set; }
        public string ActionType { get; set; }
        public string TableName { get; set; }
        public Nullable<int> RecordID { get; set; }
        public Nullable<System.DateTime> ActionTime { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
