//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingFriends.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int CustomerID { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime WeddingDate { get; set; }
        public string WeddingVenue { get; set; }
        public Nullable<decimal> Budget { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
