//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingFriends.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeddingFriendsRentalEntities : DbContext
    {
        public WeddingFriendsRentalEntities()
            : base("name=WeddingFriendsRentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActorRoleMapping> ActorRoleMapping { get; set; }
        public DbSet<ActorRoles> ActorRoles { get; set; }
        public DbSet<Actors> Actors { get; set; }
        public DbSet<AdminLogs> AdminLogs { get; set; }
        public DbSet<Customers> Customers { get; set; }
        public DbSet<OrderDetails> OrderDetails { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<ScriptRequiredRoles> ScriptRequiredRoles { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<WeddingScripts> WeddingScripts { get; set; }
    }
}
