//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingFriends.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptRequiredRoles
    {
        public int RequirementID { get; set; }
        public Nullable<int> ScriptID { get; set; }
        public Nullable<int> ActorRoleID { get; set; }
        public Nullable<int> QuantityRequired { get; set; }
    
        public virtual ActorRoles ActorRoles { get; set; }
        public virtual WeddingScripts WeddingScripts { get; set; }
    }
}
