//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingFriends.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeddingScripts
    {
        public WeddingScripts()
        {
            this.Orders = new HashSet<Orders>();
            this.ScriptRequiredRoles = new HashSet<ScriptRequiredRoles>();
        }
    
        public int ScriptID { get; set; }
        public string ScriptName { get; set; }
        public string Description { get; set; }
        public Nullable<int> RequiredRolesCount { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<ScriptRequiredRoles> ScriptRequiredRoles { get; set; }
    }
}
